// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAvLUXZGm-PO_3Iix70mRphPliIX6Mk5W8',
    appId: '1:521197592091:web:989e0c1d35ef1fc60222be',
    messagingSenderId: '521197592091',
    projectId: 'backendwork-ee42d',
    authDomain: 'backendwork-ee42d.firebaseapp.com',
    databaseURL: 'https://backendwork-ee42d-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'backendwork-ee42d.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDxNtJi3vViYHqbPmXCSyoVSEDE3S49a4s',
    appId: '1:521197592091:android:ae0bba8950f991210222be',
    messagingSenderId: '521197592091',
    projectId: 'backendwork-ee42d',
    databaseURL: 'https://backendwork-ee42d-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'backendwork-ee42d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBHbi_pmZ4FupjhYy9h92GT0s5JZqUFx68',
    appId: '1:521197592091:ios:432514ef2c5e32720222be',
    messagingSenderId: '521197592091',
    projectId: 'backendwork-ee42d',
    databaseURL: 'https://backendwork-ee42d-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'backendwork-ee42d.appspot.com',
    iosBundleId: 'com.example.machinetest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBHbi_pmZ4FupjhYy9h92GT0s5JZqUFx68',
    appId: '1:521197592091:ios:432514ef2c5e32720222be',
    messagingSenderId: '521197592091',
    projectId: 'backendwork-ee42d',
    databaseURL: 'https://backendwork-ee42d-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'backendwork-ee42d.appspot.com',
    iosBundleId: 'com.example.machinetest',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDhsWzLJ-eDgbmCCGP7e5Y5UJ3oGXorMmg',
    appId: '1:521197592091:web:5ab899eedb6ebcf80222be',
    messagingSenderId: '521197592091',
    projectId: 'backendwork-ee42d',
    authDomain: 'backendwork-ee42d.firebaseapp.com',
    databaseURL: 'https://backendwork-ee42d-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'backendwork-ee42d.appspot.com',
  );
}
